### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by sazizah** [mykle1/MMM-ToDoLive#1]
Hi! I use MMM-ToDoLive module to be able to add text directly to my magic mirror. but after I installed it, nothing happened, I couldn’t delete the default text and add text to my magic mirror.
I try to re-install and the result is same

**Comment by mykle1** [comment]
You have to click at the end of the default text when the module loads and then backspace to clear it. I just tested mine and works as expected

**Comment by sazizah** [comment]
i've tried click it at the end of the default text but nothing happend. i try to reinstall it too, but the result is same

**Comment by sazizah** [comment]
does MMM-ToDoLive compatible only with specific node js ? or it compatible with all node js version ?

**Comment by mykle1** [comment]
Sorry about the delay. I just installed this on the newest version of MM and it works fine, node version 16.13.2. 

Does it work on all versions of node? I don't know. I haven't tried with ALL versions of node
